{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compound-docs.esoServiceAccountName" . }}
  labels:
    {{- include "compound-docs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.externalSecrets | quote }}
{{- end }}
