{{- if and .Values.externalSecrets.enabled .Values.neptune.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "compound-docs.fullname" . }}-neptune
  labels:
    {{- include "compound-docs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.externalSecrets | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "compound-docs.fullname" . }}
    kind: SecretStore
  target:
    name: {{ .Values.neptune.connectionSecretName }}
    deletionPolicy: Retain
  data:
    - secretKey: endpoint
      remoteRef:
        key: {{ include "compound-docs.smSecretPath" (dict "prefix" .Values.externalSecrets.secretsManagerPrefix "service" "neptune") }}
        property: endpoint
    - secretKey: reader_endpoint
      remoteRef:
        key: {{ include "compound-docs.smSecretPath" (dict "prefix" .Values.externalSecrets.secretsManagerPrefix "service" "neptune") }}
        property: reader_endpoint
    - secretKey: port
      remoteRef:
        key: {{ include "compound-docs.smSecretPath" (dict "prefix" .Values.externalSecrets.secretsManagerPrefix "service" "neptune") }}
        property: port
{{- end }}
