{{- if and .Values.externalSecrets.enabled .Values.iam.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "compound-docs.fullname" . }}-iam
  labels:
    {{- include "compound-docs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.externalSecrets | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "compound-docs.fullname" . }}
    kind: SecretStore
  target:
    name: {{ .Values.iam.connectionSecretName }}
    deletionPolicy: Retain
  data:
    - secretKey: role_arn
      remoteRef:
        key: {{ include "compound-docs.smSecretPath" (dict "prefix" .Values.externalSecrets.secretsManagerPrefix "service" "iam") }}
        property: role_arn
{{- end }}
