{{- if and .Values.externalSecrets.enabled .Values.opensearch.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "compound-docs.fullname" . }}-opensearch
  labels:
    {{- include "compound-docs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.externalSecrets | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "compound-docs.fullname" . }}
    kind: SecretStore
  target:
    name: {{ .Values.opensearch.connectionSecretName }}
    deletionPolicy: Retain
  data:
    - secretKey: endpoint
      remoteRef:
        key: {{ include "compound-docs.smSecretPath" (dict "prefix" .Values.externalSecrets.secretsManagerPrefix "service" "opensearch") }}
        property: endpoint
    - secretKey: collection_id
      remoteRef:
        key: {{ include "compound-docs.smSecretPath" (dict "prefix" .Values.externalSecrets.secretsManagerPrefix "service" "opensearch") }}
        property: collection_id
{{- end }}
