{{- if not .Values.auth.apiKeysSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compound-docs.fullname" . }}-api-keys
  labels:
    {{- include "compound-docs.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
